In [1]:
# we are expressing yield of apples as weighted sum of temperature ,humidity, rainfall
w1,w2,w3 = 0.2,0.3,0.5

In [2]:
# can convert the tabular data into variables
del_temp=35
del_humid=87
del_rainfal=33

In [3]:
del_yield= del_temp*w1 + del_humid*w2 +del_rainfal*w3
del_yield

49.599999999999994

In [4]:
# for multiple calculations instead of making variables we can make a list or represent each variable in the form of vector
delhi=[35,87,33]
mumbai =[23,88,23]

In [5]:
weights=[w1,w2,w3]

In [6]:
# zip function returns pairs out of 2 lists ie iterate pairwise
for item in zip(delhi,weights):
    print(item)

(35, 0.2)
(87, 0.3)
(33, 0.5)


In [7]:
# multiple lists can be input to a function 
def crop_yield(city,weight):
    result=0
    for x,y in zip(city,weight):
        result += x*y
    return result

In [8]:
crop_yield(delhi,weights)

49.599999999999994

In [9]:
crop_yield(mumbai,weights)

42.5

## Numpy



numpy is used to perform mathematical functions -- above multiplication can be performed using data structure called numpy array


In [10]:
import numpy as np

In [11]:
delhi = np.array([35,87,33])

In [12]:
weights=np.array([0.2,0.3,0.5])

In [13]:
delhi

array([35, 87, 33])

In [14]:
weights

array([0.2, 0.3, 0.5])

In [15]:
type(delhi)

numpy.ndarray

just like lists numpy array also support indexing--these are no longer lists

In [16]:
delhi[1]

87

In [17]:
help(np.dot)

Help on function dot in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to :func:`multiply`
      and using ``numpy.multiply(a, b)`` or ``a * b`` is preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    Parameters
    ----------
    a : array_like
        First argument.
    b : array_like
        Second argument.
    out : 

we can achieve dot product of two vectors using np.dot() function--also we can achieve same output by doing lower level operations

In [18]:
np.dot(delhi,weights)

49.599999999999994

In [19]:
(delhi*weights).sum()

49.599999999999994

a  * performs element wise multiplication of two arrays

## benefits of numpy arrays


 numpy arrays are internally implemented using c++ which makes them faster than for loops in python as they are implemented during runtime

In [20]:
# python lists
arr1 =list(range(100))
arr2 = list(range(100, 200))

# numpy arrays
arrx = np.array(arr1)
arry = np.array(arr2)

%%time function needs to be at starting of a cell cannot even write commennts above it

In [21]:

%%time
result =0
for item1,item2 in zip(arr1,arr2):
    result+= item1*item2
result    
    


CPU times: total: 0 ns
Wall time: 0 ns


823350

In [22]:
# numpy arrays can overflow while dealing with large integers

In [23]:
%%time
np.dot(arrx, arry)



CPU times: total: 0 ns
Wall time: 0 ns


823350

## Multidimensional arrays
we need to pass a list of lists or we can say nesting of lists


In [24]:
#2-d array --we cam write in same line or in different lines
climate_data = np.array([[35,67,33],
                        [32,45,61],
                        [41,24,94],
                        [52,13,52]])

In [25]:
#3-d array --two matrices sitting side by side forming a cuboid
array_3d=np.array([
    [[23,42,32],
     [12,44,23,]],
                   
    [[34,54,23],
     [53,23,41]]])

In [26]:
climate_data.shape # sees how much elements outer list has and then inner list. 

(4, 3)

In [27]:
array_3d.shape

(2, 2, 3)

In [28]:
# all elements in a nmpy array have same datatype,we can check datatype of an array using .dtype property
climate_data.dtype

dtype('int32')

In [29]:
weights.dtype 
# 64 bits of memory will be used to store this float

dtype('float64')

In [30]:
# if an array contains a floating point number ,all the other elements will be converted to float

In [31]:
# for matrix multiplication use np.matmul function

In [32]:
np.matmul(climate_data,weights)

array([43.6, 50.4, 62.4, 40.3])

In [33]:
#OR use @ characte for matrix multiplication
climate_data @ weights

array([43.6, 50.4, 62.4, 40.3])

## working with CSV data files

In [34]:
# storing data which are separated using comma are CSV (comma separated values)

In [35]:
# to downloaad a file use urllib library and urllib.request submodule

In [36]:
import urllib.request

In [37]:
# to download use the urlretrieve function and give the function the link that needs to be downloaded

In [38]:
# download the csv file to your local storage and in the same folder in which we are running jupyter notebook or we have to 
#give full path to genfromtxt function

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv',
    'climate.txt'
)

URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

In [39]:
# to read a file into a numpy array
climate_data = np.genfromtxt('climate.txt',delimiter=',',skip_header=1)

In [40]:
climate_data

array([[32., 53., 32.],
       [93., 83., 22.],
       [53., 13., 34.],
       [28., 45., 53.],
       [28., 23., 53.],
       [82., 22., 33.]])

In [41]:
climate_data.shape

(6, 3)

In [42]:
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes', *, ndmin=0, like=None)
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must retu

In [43]:
# We can now use a matrix mulplication operator@ to predict the yield of apples for the entire dataset using a given set 
# of weights.
yields = climate_data @ weights

In [44]:
yields


array([38.3, 54.5, 31.5, 45.6, 39. , 39.5])

In [45]:
yields.shape

(6,)

In [46]:
# We can now add the yields back to climate_data as a fourth column using the np.concatenate function
# we need to give the tuple we are concatenating

In [47]:
climate_results = np.concatenate((climate_data,yields.reshape(6,1)), axis = 1)

In [48]:
climate_results

array([[32. , 53. , 32. , 38.3],
       [93. , 83. , 22. , 54.5],
       [53. , 13. , 34. , 31.5],
       [28. , 45. , 53. , 45.6],
       [28. , 23. , 53. , 39. ],
       [82. , 22. , 33. , 39.5]])

In [49]:
#Let's write the final results from our computation above back to a file using the np.savetxt function.
# fmt float upto 2 decimal points
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

In [50]:
# Numpy provides hundreds of functions for peforming operations on arrays. Here are some common functions:

#Mathematics: np.sum, np.exp, np.round, arithemtic operators
#Array manipulation: np.reshape, np.stack, np.concatenate, np.split
#Linear Algebra: np.matmul, np.dot, np.transpose, np.eigvals
#Statistics: np.mean, np.median, np.std, np.max

## Arithmatic operations and broadcasting

In [51]:
# Numpy arrays support arithmetic operators like +, -, * etc. You can perform an arithmetic operation with a single number
#(also called scalar), or with another array of the same shape.This makes it really easy to write mathemtical expressions with
#multi-dimensional arrays.

In [52]:
arr2 =np.array( [[1,2,3,4],
        [5,6,7,8],
        [9,1,2,3]])

In [53]:
arr3 = np.array([[11,12,13,14],
        [15,16,17,18],
        [19,11,12,13]])

In [54]:
# Adding a scalar
arr2 + 3

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [55]:
# Element-wise subtraction
arr3 - arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [56]:
# Division by scalar
arr2 / 2

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ],
       [4.5, 0.5, 1. , 1.5]])

In [57]:

# Element-wise multiplication
arr2 * arr3

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [58]:
# Modulus with scalar
arr2 % 4
     

array([[1, 2, 3, 0],
       [1, 2, 3, 0],
       [1, 1, 2, 3]], dtype=int32)

Numpy arrays also support brodcasting, which allows arthmetic operations between two array having a different number of dimensions, but compatible shapes. Let's look at an example to see how it works.

In [59]:
arr2.shape

(3, 4)

In [60]:
arr4 = np.array([4, 5, 6, 7])

In [61]:
arr4.shape

(4,)

In [62]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

When the expression arr2 + arr4 is evaluated, arr4 (which has the shape (4,)) is replicated 3 times to match the shape (3, 4) of arr2. This is pretty useful, because numpy performs the replication without actually creating 3 copies of the smaller dimension array.

Broadcasting only works if one of the arrays can be replicated to exactly match the shape of the other array.

In [63]:
arr5 = np.array([7, 8])

In [64]:

arr5.shape

(2,)

In [65]:
arr2 + arr5
#In the above example, even if arr5 is replicated 3 times,
#it will not match the shape of arr2, hence arr2 + arr5 cannot be evaluted successfully.

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [ ]:
#Numpy arrays also support comparision operations like ==, !=, > etc. The result is an array of booleans.

In [66]:
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

In [67]:
arr1 == arr2

array([[False,  True,  True],
       [False, False,  True]])

In [68]:
arr1 != arr2
     

array([[ True, False, False],
       [ True,  True, False]])

In [69]:
arr1 >= arr2

array([[False,  True,  True],
       [ True,  True,  True]])

In [70]:
arr1 < arr2

array([[ True, False, False],
       [False, False, False]])

In [ ]:
#A common use case for this is to count the number of equal elements in two arrays using the sum method. 
#Remember that True evalues to 1 and False evaluates to 0 when booleans are used in arithmetic operations.

In [71]:
(arr1 == arr2).sum()

3

## Array indexiing and slicing

Numpy extends Python's list indexing notation using [] to multiple dimensions in a fairly intuitive fashion. You can provide a comma separated list of indices or ranges to select a specific element or a subarray (also called slice) from a numpy array.

In [72]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [73]:
arr3.shape

(3, 2, 4)

In [74]:

# Single element
arr3[1, 1, 2]

36.0

In [75]:
# Subarray using ranges
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [76]:
# Mixing indices and ranges
arr3[1:, 1, 3]

array([18., 43.])

In [77]:
# Mixing indices and ranges
arr3[1:, 1, :3]
     

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [78]:
# Using fewer indices
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [79]:
# Using too many indices
arr3[1,3,2,1]

IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

## Other ways to create numpy arrays


Numpy also provides some handy functions to create arrays of a desired shape with fixed or random values. Check the out the official documentation or use the help function to learn more about the following functions

In [80]:
# All zeros
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [81]:
# All ones
np.ones([2, 2, 3])

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [82]:
# Identity matrix
np.eye(3)
     

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [83]:
# Random vector--it will generate 5 random values between 0 and 1
np.random.rand(5)

array([0.75832005, 0.50883202, 0.6482687 , 0.98527091, 0.70239012])

In [84]:
# Random matrix-- generate random values from a gaussian surface--generally ranges between -2 to 2
# does not take tuple as an input ie randn((2,3)) will give error
np.random.randn(2, 3)

array([[ 0.07442055, -0.13317191, -1.1671661 ],
       [ 1.49645693,  0.74748738,  0.0391827 ]])

In [85]:

# Fixed value
np.full([2, 3], 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [86]:
# Range with start, end and step
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [88]:
np.arange(10,90,3).shape

(27,)

In [91]:
np.arange(10,90,3).reshape(3,3,-1) # can just reshape in size of number of elements present
# if -1 is given as an attribute  it will automaticaly figuure out the shape in which it has to be formed according to number 
# of elements present

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [87]:
# Equally spaced numbers in a range
np.linspace(3, 27, 9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [90]:
np.linspace(3, 27, 9).reshape(3,3)

array([[ 3.,  6.,  9.],
       [12., 15., 18.],
       [21., 24., 27.]])